### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [mattneub/AsciiDoc-TextMate-2.tmbundle#2]
I would like to use your grammar for AsciiDoc but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by davidpriest** [comment]
I have a grammar?

Paul Chaignon wrote:

**Comment by davidpriest** [comment]
Matt Neub: your github email appears to send messages to me.  Please remedy.

David Priest wrote:

**Comment by pchaigno** [comment]
@davidpriest I was writing for @mattneub, the owner of this repository. Unless you're a co-owner?
<br/>

> Matt Neub: your github email appears to send messages to me. Please remedy.

That's probably because [you're watching this repository](https://github.com/mattneub/AsciiDoc-TextMate-2.tmbundle/watchers).

**Comment by davidpriest** [comment]
Ah!  I'll go check my own mail settings, then!

Paul Chaignon wrote:

**Comment by mattneub** [comment]
Probably MIT (http://choosealicense.com/licenses/mit/). This seems closest to the Markdown bundle license which is what I would want to imitate. Do what you want with it, don't pretend you wrote it if you didn't, and good luck to you. :) Seriously, I'm delighted at the prospect of having an actual user. There are some mild syntax-coloring bugs but I've been too busy using this bundle to correct them!

**Comment by pchaigno** [comment]
Thanks! Could you add the license as a file in the repository or in the README?
