### ISSUE TITLE
call asciidoctor to generate html when save the file

### ISSUE THREAD

**Issue by xu4wang** [mattneub/AsciiDoc-TextMate-2.tmbundle#6]
The scenario for me to use textmate and asciidoctor is

1. Edit asciidoc files with textmate
2. Save
3. call asciidoctor via console to generate html
4. refresh the browser to validate everything is fine

Is there a way to automate the step #3 above?

Thanks,Austin

**Comment by davidpriest** [comment]
fswatch

See https://stackoverflow.com/questions/1515730/is-there-a-command-like-watch-or-inotifywait-on-the-mac

Works a charm for me.

**Comment by xu4wang** [comment]
> fswatch See https://stackoverflow.com/questions/1515730/is-there-a-command-like-watch-or-inotifywait-on-the-mac Works a charm for me.
> […](#)
> On May 1, 2020, at 6:54 PM, Austin (Xu) Wang ***@***.***> wrote: ﻿ The scenario for me to use textmate and asciidoctor is Edit asciidoc files with textmate Save call asciidoctor via console to generate html refresh the browser to validate everything is fine Is there a way to automate the step #3 above? Thanks,Austin — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

thanks @davidpriest  it looks good.

Maybe textmate can do that too? if can, the process can be a little bit shorter. :-)

**Comment by xu4wang** [comment]
OK. I am using 

```
Bundles -> AsciiDoc -> Preview Document
```

Assigned one short cut key, it's very convenient for me.
